typedef struct Npfcall Npfcall;

struct Npfcall {
	u32		size;
	u8	type;
	u16		tag;
	u8*		pkt;
	union {
	   struct p9_rlerror rlerror;
	   struct p9_tstatfs tstatfs;
	   struct p9_rstatfs rstatfs;
	   struct p9_tlopen tlopen;
	   struct p9_rlopen rlopen;
	   struct p9_tlcreate tlcreate;
	   struct p9_rlcreate rlcreate;
	   struct p9_tsymlink tsymlink;
	   struct p9_rsymlink rsymlink;
	   struct p9_tmknod tmknod;
	   struct p9_rmknod rmknod;
	   struct p9_trename trename;
	   struct p9_rrename rrename;
	   struct p9_treadlink treadlink;
	   struct p9_rreadlink rreadlink;
	   struct p9_tgetattr tgetattr;
	   struct p9_rgetattr rgetattr;
	   struct p9_tsetattr tsetattr;
	   struct p9_rsetattr rsetattr;
	   struct p9_txattrwalk txattrwalk;
	   struct p9_rxattrwalk rxattrwalk;
	   struct p9_txattrcreate txattrcreate;
	   struct p9_rxattrcreate rxattrcreate;
	   struct p9_treaddir treaddir;
	   struct p9_rreaddir rreaddir;
	   struct p9_tfsync tfsync;
	   struct p9_rfsync rfsync;
	   struct p9_tlock tlock;
	   struct p9_rlock rlock;
	   struct p9_tgetlock tgetlock;
	   struct p9_rgetlock rgetlock;
	   struct p9_tlink tlink;
	   struct p9_rlink rlink;
	   struct p9_tmkdir tmkdir;
	   struct p9_rmkdir rmkdir;
	   struct p9_trenameat trenameat;
	   struct p9_rrenameat rrenameat;
	   struct p9_tunlinkat tunlinkat;
	   struct p9_runlinkat runlinkat;

	   struct p9_tversion tversion;
	   struct p9_rversion rversion;
	   struct p9_tauth tauth;
	   struct p9_rauth rauth;
	   struct p9_tattach tattach;
	   struct p9_rattach rattach;
	   struct p9_tflush tflush;
	   struct p9_rflush rflush;
	   struct p9_twalk twalk;
	   struct p9_rwalk rwalk;
	   struct p9_tread tread;
	   struct p9_rread rread;
	   struct p9_twrite twrite;
	   struct p9_rwrite rwrite;
	   struct p9_tclunk tclunk;
	   struct p9_rclunk rclunk;
	   struct p9_tremove tremove;
	   struct p9_rremove rremove;
	} u;
};
